### ISSUE TITLE
(1/1) #1256475113 InvalidArgumentException

### ISSUE THREAD

**Issue by Kathara** [neuedaten/svg-embed#1]
Hey, just wanted to inform you, that using this viewhelper with a fileReference creates an InvalidArgumentException with following message:

The argument "src" was registered with type "", but is of type "TYPO3\CMS\Core\Resource\FileReference" in view helper "Neuedaten\SvgEmbed\ViewHelpers\SvgEmbedViewHelper".

changing
`$this->registerArgument('src', '', 'The svg file path to embed', true);`
to
`$this->registerArgument('src', 'mixed', 'The svg file path to embed', true);`

solves the problem for TYPO3 v9.5 (running on PHP 7.3).

I didn't test other sources, but will probably result in the same error message.

Also, you should update the readme as you have an incorrect srcType as example:
`<neuedaten:svgEmbed src="{falObject}" srcType="FAL"/>`
should be
`<neuedaten:svgEmbed src="{falObject}" srcType="FAL_OBJECT"/>`

or change the code (constant) accordingly ;-)

Have a nice day.

**Comment by taherbensassi** [comment]
i Have also the same problem but i have changed like this, and it' working also:
    ` $this->registerArgument('src', \TYPO3\CMS\Core\Resource\FileReference::class, 'The svg file path to embed', true);`

**Comment by r12r** [comment]
@Kathara @taherbensassi 
Thank you both for your feedback! 
Today I finally found some time to fix the ext and create a new version.

Have a nice weekend!
